#Build go executable
FROM golang:1.20 as builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download && go mod verify
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -v -o /app/backend .

#Run go executable
FROM alpine:latest as runner
WORKDIR /app
COPY --from=builder /app/backend /app/backend
CMD ["./backend"]