# Build stage for the Go executable
FROM golang:1.22 as builder

# Install Air
RUN go install github.com/cosmtrek/air@v1.29.0
RUN go install github.com/swaggo/swag/cmd/swag@latest

# Set the working directory inside the container
WORKDIR /app

# Copy go.mod and go.sum files first
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Expose the port your app runs on
EXPOSE 8080

# Command to run the Air tool
CMD ["air"]
