# Build go executable
FROM golang:1.22 as builder

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download and verify go dependencies
RUN go mod download && go mod verify

# Install air for live reloading
RUN go install github.com/air-verse/air@latest
RUN air init

# Expose the port that your application listens on (adjust as needed)
EXPOSE 8080

# Command to run air
CMD ["air", "-c", ".air.toml" ]
