// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/graphs": {
            "get": {
                "description": "get all graphs from the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "graphs"
                ],
                "summary": "Retrieve all graphs",
                "responses": {
                    "200": {
                        "description": "List of graphs",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Graph"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "description": "create a new graph with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "graphs"
                ],
                "summary": "Create a new graph",
                "parameters": [
                    {
                        "description": "Graph Info",
                        "name": "graph",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Graph"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successfully created",
                        "schema": {
                            "$ref": "#/definitions/models.Graph"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid JSON",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "422": {
                        "description": "Bad request - missing element",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/graphs/{id}": {
            "get": {
                "description": "get graph by ID from the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "graphs"
                ],
                "summary": "Retrieve a graph by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Graph ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Graph retrieved",
                        "schema": {
                            "$ref": "#/definitions/models.Graph"
                        }
                    },
                    "404": {
                        "description": "Graph not found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            },
            "put": {
                "description": "update details of a graph by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "graphs"
                ],
                "summary": "Update a graph",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Graph ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Graph info",
                        "name": "graph",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Graph"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Graph updated",
                        "schema": {
                            "$ref": "#/definitions/models.Graph"
                        }
                    },
                    "404": {
                        "description": "Graph not found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete a graph by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "graphs"
                ],
                "summary": "Delete a graph",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Graph ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Graph not found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/matches": {
            "get": {
                "description": "get all matches from the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matches"
                ],
                "summary": "Retrieve all matches",
                "responses": {
                    "200": {
                        "description": "List of matches",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Match"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "description": "create a new match with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matches"
                ],
                "summary": "Create a new match",
                "parameters": [
                    {
                        "description": "Match Info",
                        "name": "match",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Match"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successfully created",
                        "schema": {
                            "$ref": "#/definitions/models.Match"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid JSON",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "422": {
                        "description": "Bad request - missing element",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/matches/{id}": {
            "get": {
                "description": "get match by ID from the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matches"
                ],
                "summary": "Retrieve a match by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Match ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Match retrieved",
                        "schema": {
                            "$ref": "#/definitions/models.Match"
                        }
                    },
                    "404": {
                        "description": "Match not found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            },
            "put": {
                "description": "update details of a match by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matches"
                ],
                "summary": "Update a match",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Match ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Match info",
                        "name": "match",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Match"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Match updated",
                        "schema": {
                            "$ref": "#/definitions/models.Match"
                        }
                    },
                    "404": {
                        "description": "Match not found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete a match by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matches"
                ],
                "summary": "Delete a match",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Match ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Match not found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/spreadsheets": {
            "get": {
                "description": "get all spreadsheets from the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spreadsheets"
                ],
                "summary": "Retrieve all spreadsheets",
                "responses": {
                    "200": {
                        "description": "List of spreadsheets",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Spreadsheet"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "description": "create a new spreadsheet with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spreadsheets"
                ],
                "summary": "Create a new spreadsheet",
                "parameters": [
                    {
                        "description": "Spreadsheet Info",
                        "name": "spreadsheet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Spreadsheet"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successfully created",
                        "schema": {
                            "$ref": "#/definitions/models.Spreadsheet"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid JSON",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "422": {
                        "description": "Bad request - missing element",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/spreadsheets/{id}": {
            "get": {
                "description": "get spreadsheet by ID from the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spreadsheets"
                ],
                "summary": "Retrieve a spreadsheet by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Spreadsheet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Spreadsheet retrieved",
                        "schema": {
                            "$ref": "#/definitions/models.Spreadsheet"
                        }
                    },
                    "404": {
                        "description": "Spreadsheet not found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            },
            "put": {
                "description": "update details of a spreadsheet by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spreadsheets"
                ],
                "summary": "Update a spreadsheet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Spreadsheet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Spreadsheet info",
                        "name": "spreadsheet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Spreadsheet"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Spreadsheet updated",
                        "schema": {
                            "$ref": "#/definitions/models.Spreadsheet"
                        }
                    },
                    "404": {
                        "description": "Spreadsheet not found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete a spreadsheet by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spreadsheets"
                ],
                "summary": "Delete a spreadsheet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Spreadsheet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Spreadsheet not found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Graph": {
            "type": "object",
            "properties": {
                "datasource": {
                    "type": "string"
                },
                "graphType": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.HTTPError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.Match": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "thirds": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "models.Spreadsheet": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {}
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Tchoukball Tracker API",
	Description:      "Tchoukball Tracker API documentation.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
