name: Cloud App Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install flake8
      run: pip install flake8

    - name: Run flake8 and generate report
      run: flake8 . --max-line-length=120 --exit-zero --output-file flake8_report.txt

    - name: Build with docker compose
      run: docker compose build

    - name: Save Docker image
      run: docker save bs3221-developing-for-the-cloud-app:latest -o bs3221-developing-for-the-cloud-app.tar

    - name: Compress Docker image
      run: gzip bs3221-developing-for-the-cloud-app.tar

    - name: Upload flake8 report
      uses: actions/upload-artifact@v4
      with:
        name: flake8-report
        path: flake8_report.txt

    - name: Upload Docker image
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: bs3221-developing-for-the-cloud-app.tar.gz
